### ISSUE TITLE
Lack of config.py and sample apk

### ISSUE THREAD

**Issue by Vmmmg** [columbia/appflow#1]
Error when start appflow : 
Traceback (most recent call last):
  File "/Users/root/appflow-master/appflow-master/src/app.py", line 3, in <module>
    import sense
  File "/Users/root/appflow-master/appflow-master/src/sense.py", line 3, in <module>
    import config
ModuleNotFoundError: No module named 'config'

May you supply us your config file and experimental apks? 
Here is my contact 151070025@smail.nju.edu.cn. Thanks a lot

**Comment by Vmmmg** [comment]
models and GUIs are also in need

**Comment by Yiliayan** [comment]
I have the same question. May you supply us your config file and experimental apks?

**Comment by Yiliayan** [comment]
Is this problem solved？I also encountered this problem.
